name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/tests/build -S ${{ github.workspace }}/tests -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/tests/build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --test-dir ${{ github.workspace }}/tests/build --output-on-failure
